/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import qrmascota.conexion;

/**
 *
 * @author Marcelo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    int xMouse, yMouse;

    public Inicio() {
        initComponents();
        this.setTitle("QR Mascotas");
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_cerrar = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel_agregar = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JLabel();
        panel_reportar = new javax.swing.JPanel();
        btn_reportar = new javax.swing.JLabel();
        panel_listado = new javax.swing.JPanel();
        btn_listado = new javax.swing.JLabel();
        panel_buscarHogar = new javax.swing.JPanel();
        btn_buscarHogar = new javax.swing.JLabel();
        panel_recuperarQR = new javax.swing.JPanel();
        btn_recuperarQR = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_cerrar.setBackground(new java.awt.Color(153, 0, 0));
        panel_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cerrar.setText("X");
        btn_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_cerrarLayout = new javax.swing.GroupLayout(panel_cerrar);
        panel_cerrar.setLayout(panel_cerrarLayout);
        panel_cerrarLayout.setHorizontalGroup(
            panel_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_cerrarLayout.setVerticalGroup(
            panel_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panel_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_agregar.setBackground(new java.awt.Color(51, 51, 51));
        panel_agregar.setForeground(new java.awt.Color(255, 255, 255));
        panel_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_agregar.setBackground(new java.awt.Color(51, 51, 51));
        btn_agregar.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar.setText("Agregar Mascota");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_agregarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_agregarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(panel_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 300, 35));

        panel_reportar.setBackground(new java.awt.Color(51, 51, 51));

        btn_reportar.setBackground(new java.awt.Color(51, 51, 51));
        btn_reportar.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        btn_reportar.setForeground(new java.awt.Color(255, 255, 255));
        btn_reportar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_reportar.setText("Reportar mi Mascota");
        btn_reportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reportarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reportarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reportarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_reportarLayout = new javax.swing.GroupLayout(panel_reportar);
        panel_reportar.setLayout(panel_reportarLayout);
        panel_reportarLayout.setHorizontalGroup(
            panel_reportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(panel_reportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_reportarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_reportar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_reportarLayout.setVerticalGroup(
            panel_reportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(panel_reportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_reportarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_reportar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(panel_reportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 300, 35));

        panel_listado.setBackground(new java.awt.Color(51, 51, 51));

        btn_listado.setBackground(new java.awt.Color(51, 51, 51));
        btn_listado.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        btn_listado.setForeground(new java.awt.Color(255, 255, 255));
        btn_listado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_listado.setText("Listado de Mascotas perdidas");
        btn_listado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_listadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_listadoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_listadoLayout = new javax.swing.GroupLayout(panel_listado);
        panel_listado.setLayout(panel_listadoLayout);
        panel_listadoLayout.setHorizontalGroup(
            panel_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(panel_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_listadoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_listadoLayout.setVerticalGroup(
            panel_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(panel_listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_listadoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(panel_listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 300, 35));

        panel_buscarHogar.setBackground(new java.awt.Color(51, 51, 51));

        btn_buscarHogar.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        btn_buscarHogar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscarHogar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buscarHogar.setText("Mascota abandonada? Buscale un hogar!");
        btn_buscarHogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscarHogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarHogarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarHogarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarHogarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_buscarHogarLayout = new javax.swing.GroupLayout(panel_buscarHogar);
        panel_buscarHogar.setLayout(panel_buscarHogarLayout);
        panel_buscarHogarLayout.setHorizontalGroup(
            panel_buscarHogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(panel_buscarHogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_buscarHogarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_buscarHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_buscarHogarLayout.setVerticalGroup(
            panel_buscarHogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(panel_buscarHogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_buscarHogarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_buscarHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(panel_buscarHogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 35));

        panel_recuperarQR.setBackground(new java.awt.Color(51, 51, 51));

        btn_recuperarQR.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        btn_recuperarQR.setForeground(new java.awt.Color(255, 255, 255));
        btn_recuperarQR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_recuperarQR.setText("Recuperar QR");
        btn_recuperarQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_recuperarQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_recuperarQRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_recuperarQRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_recuperarQRMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_recuperarQRLayout = new javax.swing.GroupLayout(panel_recuperarQR);
        panel_recuperarQR.setLayout(panel_recuperarQRLayout);
        panel_recuperarQRLayout.setHorizontalGroup(
            panel_recuperarQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(panel_recuperarQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_recuperarQRLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_recuperarQR, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_recuperarQRLayout.setVerticalGroup(
            panel_recuperarQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(panel_recuperarQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_recuperarQRLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_recuperarQR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(panel_recuperarQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 300, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 570));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 570));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 400, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarMouseClicked

    private void btn_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarMouseEntered
        // TODO add your handling code here:
        panel_cerrar.setBackground(Color.red);
    }//GEN-LAST:event_btn_cerrarMouseEntered

    private void btn_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarMouseExited
        // TODO add your handling code here:
        panel_cerrar.setBackground(new Color(153, 0, 0));
    }//GEN-LAST:event_btn_cerrarMouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        // TODO add your handling code here:

        Agregar x = new Agregar();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_reportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportarMouseClicked
        // TODO add your handling code here:
        Reportar x = new Reportar();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_reportarMouseClicked

    private void btn_listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listadoMouseClicked
        // TODO add your handling code here:
        Listado x = new Listado();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_listadoMouseClicked

    private void btn_buscarHogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarHogarMouseClicked
        // TODO add your handling code here:
        BuscarHogar x = new BuscarHogar();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_buscarHogarMouseClicked

    private void btn_recuperarQRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recuperarQRMouseClicked
        // TODO add your handling code here:
        RecuperarQR x = new RecuperarQR();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_recuperarQRMouseClicked

    private void btn_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseEntered
        // TODO add your handling code here:
        btn_agregar.setFont(new Font("Candara", Font.BOLD, 14));
    }//GEN-LAST:event_btn_agregarMouseEntered

    private void btn_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseExited
        // TODO add your handling code here:
        btn_agregar.setFont(new Font("Candara", Font.BOLD, 12));
    }//GEN-LAST:event_btn_agregarMouseExited

    private void btn_recuperarQRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recuperarQRMouseEntered
        // TODO add your handling code here:
        btn_recuperarQR.setFont(new Font("Candara", Font.BOLD, 14));
    }//GEN-LAST:event_btn_recuperarQRMouseEntered

    private void btn_recuperarQRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recuperarQRMouseExited
        // TODO add your handling code here:
        btn_recuperarQR.setFont(new Font("Candara", Font.BOLD, 12));
    }//GEN-LAST:event_btn_recuperarQRMouseExited

    private void btn_buscarHogarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarHogarMouseEntered
        // TODO add your handling code here:
        btn_buscarHogar.setFont(new Font("Candara", Font.BOLD, 14));
    }//GEN-LAST:event_btn_buscarHogarMouseEntered

    private void btn_buscarHogarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarHogarMouseExited
        // TODO add your handling code here:
        btn_buscarHogar.setFont(new Font("Candara", Font.BOLD, 12));
    }//GEN-LAST:event_btn_buscarHogarMouseExited

    private void btn_reportarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportarMouseEntered
        // TODO add your handling code here:
        btn_reportar.setFont(new Font("Candara", Font.BOLD, 14));
    }//GEN-LAST:event_btn_reportarMouseEntered

    private void btn_reportarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportarMouseExited
        // TODO add your handling code here:
        btn_reportar.setFont(new Font("Candara", Font.BOLD, 12));
    }//GEN-LAST:event_btn_reportarMouseExited

    private void btn_listadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listadoMouseEntered
        // TODO add your handling code here:
        btn_listado.setFont(new Font("Candara", Font.BOLD, 14));
    }//GEN-LAST:event_btn_listadoMouseEntered

    private void btn_listadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listadoMouseExited
        // TODO add your handling code here:
        btn_listado.setFont(new Font("Candara", Font.BOLD, 12));
    }//GEN-LAST:event_btn_listadoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_agregar;
    private javax.swing.JLabel btn_buscarHogar;
    private javax.swing.JLabel btn_cerrar;
    private javax.swing.JLabel btn_listado;
    private javax.swing.JLabel btn_recuperarQR;
    private javax.swing.JLabel btn_reportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_buscarHogar;
    private javax.swing.JPanel panel_cerrar;
    private javax.swing.JPanel panel_listado;
    private javax.swing.JPanel panel_recuperarQR;
    private javax.swing.JPanel panel_reportar;
    // End of variables declaration//GEN-END:variables
}
